# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'combine_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_combine_window(object):
    def setupUi(self, combine_window):
        combine_window.setObjectName("combine_window")
        combine_window.resize(593, 564)
        self.combine_font = QtWidgets.QWidget(combine_window)
        self.combine_font.setGeometry(QtCore.QRect(0, 0, 581, 541))
        self.combine_font.setObjectName("combine_font")
        self.result_func = QtWidgets.QPushButton(self.combine_font)
        self.result_func.setGeometry(QtCore.QRect(460, 170, 81, 71))
        self.result_func.setObjectName("result_func")
        self.result_func_introduction = QtWidgets.QPushButton(self.combine_font)
        self.result_func_introduction.setGeometry(QtCore.QRect(460, 250, 81, 21))
        self.result_func_introduction.setObjectName("result_func_introduction")
        self.combine_frame = QtWidgets.QFrame(self.combine_font)
        self.combine_frame.setGeometry(QtCore.QRect(10, 10, 411, 381))
        self.combine_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.combine_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.combine_frame.setObjectName("combine_frame")
        self.combine_frame_label = QtWidgets.QLabel(self.combine_frame)
        self.combine_frame_label.setGeometry(QtCore.QRect(5, 7, 45, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.combine_frame_label.setFont(font)
        self.combine_frame_label.setObjectName("combine_frame_label")
        self.combine_button_resetlayout = QtWidgets.QPushButton(self.combine_frame)
        self.combine_button_resetlayout.setGeometry(QtCore.QRect(320, 10, 80, 23))
        self.combine_button_resetlayout.setObjectName("combine_button_resetlayout")
        self.combine_button_addtunnel = QtWidgets.QPushButton(self.combine_frame)
        self.combine_button_addtunnel.setGeometry(QtCore.QRect(230, 10, 80, 23))
        self.combine_button_addtunnel.setObjectName("combine_button_addtunnel")
        self.combine_button_addtool = QtWidgets.QPushButton(self.combine_frame)
        self.combine_button_addtool.setGeometry(QtCore.QRect(140, 10, 80, 23))
        self.combine_button_addtool.setObjectName("combine_button_addtool")
        self.equal_label = QtWidgets.QLabel(self.combine_font)
        self.equal_label.setGeometry(QtCore.QRect(430, 210, 16, 16))
        self.equal_label.setStyleSheet("font: 20pt \"Arial\";")
        self.equal_label.setObjectName("equal_label")
        self.selected_func = QtWidgets.QWidget(self.combine_font)
        self.selected_func.setGeometry(QtCore.QRect(0, 400, 581, 141))
        self.selected_func.setObjectName("selected_func")
        self.selected_func_label = QtWidgets.QLabel(self.selected_func)
        self.selected_func_label.setGeometry(QtCore.QRect(5, 7, 91, 16))
        self.selected_func_label.setObjectName("selected_func_label")
        self.selected_clear_component = QtWidgets.QPushButton(self.selected_func)
        self.selected_clear_component.setGeometry(QtCore.QRect(500, 4, 75, 23))
        self.selected_clear_component.setObjectName("selected_clear_component")
        self.selected_clear_tunnel = QtWidgets.QPushButton(self.selected_func)
        self.selected_clear_tunnel.setGeometry(QtCore.QRect(420, 4, 75, 23))
        self.selected_clear_tunnel.setObjectName("selected_clear_tunnel")
        self.selected_clear_tool = QtWidgets.QPushButton(self.selected_func)
        self.selected_clear_tool.setGeometry(QtCore.QRect(340, 4, 75, 23))
        self.selected_clear_tool.setObjectName("selected_clear_tool")
        self.selected_widget = QtWidgets.QWidget(self.selected_func)
        self.selected_widget.setGeometry(QtCore.QRect(0, 30, 581, 111))
        self.selected_widget.setObjectName("selected_widget")
        self.button_openvariable = QtWidgets.QPushButton(self.combine_font)
        self.button_openvariable.setGeometry(QtCore.QRect(440, 10, 121, 41))
        self.button_openvariable.setObjectName("button_openvariable")

        self.retranslateUi(combine_window)
        QtCore.QMetaObject.connectSlotsByName(combine_window)

    def retranslateUi(self, combine_window):
        _translate = QtCore.QCoreApplication.translate
        combine_window.setWindowTitle(_translate("combine_window", "炼金工坊"))
        self.result_func.setToolTip(_translate("combine_window", "<html><head/><body><p>点击测试</p></body></html>"))
        self.result_func.setText(_translate("combine_window", "成品演示？"))
        self.result_func_introduction.setText(_translate("combine_window", "设置功能说明"))
        self.combine_frame_label.setText(_translate("combine_window", "合成栏"))
        self.combine_button_resetlayout.setText(_translate("combine_window", "重设布局"))
        self.combine_button_addtunnel.setText(_translate("combine_window", "添加通道部件"))
        self.combine_button_addtool.setText(_translate("combine_window", "添加工具部件"))
        self.equal_label.setText(_translate("combine_window", "="))
        self.selected_func_label.setText(_translate("combine_window", "预选区域"))
        self.selected_clear_component.setText(_translate("combine_window", "清空配件栏"))
        self.selected_clear_tunnel.setText(_translate("combine_window", "清空通道栏"))
        self.selected_clear_tool.setText(_translate("combine_window", "清空工具栏"))
        self.button_openvariable.setText(_translate("combine_window", "查看变量和结果集"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    combine_window = QtWidgets.QWidget()
    ui = Ui_combine_window()
    ui.setupUi(combine_window)
    combine_window.show()
    sys.exit(app.exec_())
