# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'combine_openvariable_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_combine_openvariable_dialog(object):
    def setupUi(self, combine_openvariable_dialog):
        combine_openvariable_dialog.setObjectName("combine_openvariable_dialog")
        combine_openvariable_dialog.resize(419, 311)
        self.gridLayout = QtWidgets.QGridLayout(combine_openvariable_dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_variable = QtWidgets.QWidget(combine_openvariable_dialog)
        self.widget_variable.setObjectName("widget_variable")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_variable)
        self.gridLayout_3.setContentsMargins(0, 2, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_variable = QtWidgets.QLabel(self.widget_variable)
        self.label_variable.setObjectName("label_variable")
        self.gridLayout_3.addWidget(self.label_variable, 0, 0, 1, 1)
        self.add_variable = QtWidgets.QPushButton(self.widget_variable)
        self.add_variable.setObjectName("add_variable")
        self.gridLayout_3.addWidget(self.add_variable, 0, 1, 1, 1)
        self.listWidget_variable = QtWidgets.QListWidget(self.widget_variable)
        self.listWidget_variable.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.listWidget_variable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listWidget_variable.setObjectName("listWidget_variable")
        self.gridLayout_3.addWidget(self.listWidget_variable, 1, 0, 1, 2)
        self.gridLayout.addWidget(self.widget_variable, 1, 1, 1, 1)
        self.widget_result = QtWidgets.QWidget(combine_openvariable_dialog)
        self.widget_result.setObjectName("widget_result")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_result)
        self.gridLayout_2.setContentsMargins(0, 2, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_result = QtWidgets.QLabel(self.widget_result)
        self.label_result.setObjectName("label_result")
        self.gridLayout_2.addWidget(self.label_result, 0, 0, 1, 1)
        self.add_result = QtWidgets.QPushButton(self.widget_result)
        self.add_result.setObjectName("add_result")
        self.gridLayout_2.addWidget(self.add_result, 0, 1, 1, 1)
        self.listWidget_result = QtWidgets.QListWidget(self.widget_result)
        self.listWidget_result.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.listWidget_result.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listWidget_result.setObjectName("listWidget_result")
        self.gridLayout_2.addWidget(self.listWidget_result, 1, 0, 1, 2)
        self.gridLayout.addWidget(self.widget_result, 1, 2, 1, 1)

        self.retranslateUi(combine_openvariable_dialog)
        QtCore.QMetaObject.connectSlotsByName(combine_openvariable_dialog)

    def retranslateUi(self, combine_openvariable_dialog):
        _translate = QtCore.QCoreApplication.translate
        combine_openvariable_dialog.setWindowTitle(_translate("combine_openvariable_dialog", "变量与结果集"))
        self.label_variable.setText(_translate("combine_openvariable_dialog", "手动输入变量"))
        self.add_variable.setText(_translate("combine_openvariable_dialog", "添加变量"))
        self.label_result.setText(_translate("combine_openvariable_dialog", "使用到的输出"))
        self.add_result.setText(_translate("combine_openvariable_dialog", "添加结果"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    combine_openvariable_dialog = QtWidgets.QDialog()
    ui = Ui_combine_openvariable_dialog()
    ui.setupUi(combine_openvariable_dialog)
    combine_openvariable_dialog.show()
    sys.exit(app.exec_())
