# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'combine_buttons_tool_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_combine_buttons_tool_dialog(object):
    def setupUi(self, combine_buttons_tool_dialog):
        combine_buttons_tool_dialog.setObjectName("combine_buttons_tool_dialog")
        combine_buttons_tool_dialog.resize(449, 443)
        self.gridLayout = QtWidgets.QGridLayout(combine_buttons_tool_dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(combine_buttons_tool_dialog)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(combine_buttons_tool_dialog)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(combine_buttons_tool_dialog)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.comboBox_variable = QtWidgets.QComboBox(combine_buttons_tool_dialog)
        self.comboBox_variable.setObjectName("comboBox_variable")
        self.gridLayout.addWidget(self.comboBox_variable, 2, 1, 1, 1)
        self.toolButton_variable = QtWidgets.QToolButton(combine_buttons_tool_dialog)
        self.toolButton_variable.setText("")
        self.toolButton_variable.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.toolButton_variable.setAutoRaise(True)
        self.toolButton_variable.setObjectName("toolButton_variable")
        self.gridLayout.addWidget(self.toolButton_variable, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(combine_buttons_tool_dialog)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.toolButton_variable_value = QtWidgets.QToolButton(combine_buttons_tool_dialog)
        self.toolButton_variable_value.setText("")
        self.toolButton_variable_value.setAutoRaise(True)
        self.toolButton_variable_value.setArrowType(QtCore.Qt.NoArrow)
        self.toolButton_variable_value.setObjectName("toolButton_variable_value")
        self.gridLayout.addWidget(self.toolButton_variable_value, 3, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(combine_buttons_tool_dialog)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(combine_buttons_tool_dialog)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.lineEdit_result_name = QtWidgets.QLineEdit(combine_buttons_tool_dialog)
        self.lineEdit_result_name.setFrame(False)
        self.lineEdit_result_name.setReadOnly(True)
        self.lineEdit_result_name.setObjectName("lineEdit_result_name")
        self.gridLayout.addWidget(self.lineEdit_result_name, 5, 1, 1, 1)
        self.toolButton_result_name = QtWidgets.QToolButton(combine_buttons_tool_dialog)
        self.toolButton_result_name.setText("")
        self.toolButton_result_name.setAutoRaise(True)
        self.toolButton_result_name.setObjectName("toolButton_result_name")
        self.gridLayout.addWidget(self.toolButton_result_name, 5, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(combine_buttons_tool_dialog)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.widget_component = QtWidgets.QWidget(combine_buttons_tool_dialog)
        self.widget_component.setObjectName("widget_component")
        self.gridLayout.addWidget(self.widget_component, 6, 1, 1, 2)
        self.lineEdit_name = QtWidgets.QLineEdit(combine_buttons_tool_dialog)
        self.lineEdit_name.setFrame(False)
        self.lineEdit_name.setReadOnly(True)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.gridLayout.addWidget(self.lineEdit_name, 0, 1, 1, 2)
        self.lineEdit_command = QtWidgets.QLineEdit(combine_buttons_tool_dialog)
        self.lineEdit_command.setFrame(False)
        self.lineEdit_command.setReadOnly(True)
        self.lineEdit_command.setObjectName("lineEdit_command")
        self.gridLayout.addWidget(self.lineEdit_command, 1, 1, 1, 2)
        self.lineEdit_variable_value = QtWidgets.QLineEdit(combine_buttons_tool_dialog)
        self.lineEdit_variable_value.setFrame(False)
        self.lineEdit_variable_value.setReadOnly(True)
        self.lineEdit_variable_value.setObjectName("lineEdit_variable_value")
        self.gridLayout.addWidget(self.lineEdit_variable_value, 3, 1, 1, 1)
        self.comboBox_result = QtWidgets.QComboBox(combine_buttons_tool_dialog)
        self.comboBox_result.setObjectName("comboBox_result")
        self.gridLayout.addWidget(self.comboBox_result, 4, 1, 1, 2)

        self.retranslateUi(combine_buttons_tool_dialog)
        QtCore.QMetaObject.connectSlotsByName(combine_buttons_tool_dialog)

    def retranslateUi(self, combine_buttons_tool_dialog):
        _translate = QtCore.QCoreApplication.translate
        combine_buttons_tool_dialog.setWindowTitle(_translate("combine_buttons_tool_dialog", "工具部件详情"))
        self.label.setText(_translate("combine_buttons_tool_dialog", "工具"))
        self.label_4.setText(_translate("combine_buttons_tool_dialog", "命令"))
        self.label_2.setText(_translate("combine_buttons_tool_dialog", "命令变量"))
        self.label_3.setText(_translate("combine_buttons_tool_dialog", "变量值"))
        self.label_7.setText(_translate("combine_buttons_tool_dialog", "输出变量"))
        self.label_5.setText(_translate("combine_buttons_tool_dialog", "输出别名"))
        self.lineEdit_result_name.setPlaceholderText(_translate("combine_buttons_tool_dialog", "请输入变量别名，留空为不使用"))
        self.label_6.setText(_translate("combine_buttons_tool_dialog", "配件"))
        self.lineEdit_variable_value.setPlaceholderText(_translate("combine_buttons_tool_dialog", "请选择变量输入值，留空为不使用"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    combine_buttons_tool_dialog = QtWidgets.QDialog()
    ui = Ui_combine_buttons_tool_dialog()
    ui.setupUi(combine_buttons_tool_dialog)
    combine_buttons_tool_dialog.show()
    sys.exit(app.exec_())
