# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'combine_func_detatil_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_combine_func_detatil_dialog(object):
    def setupUi(self, combine_func_detatil_dialog):
        combine_func_detatil_dialog.setObjectName("combine_func_detatil_dialog")
        combine_func_detatil_dialog.resize(546, 466)
        self.verticalLayout = QtWidgets.QVBoxLayout(combine_func_detatil_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_name = QtWidgets.QLineEdit(combine_func_detatil_dialog)
        self.lineEdit_name.setReadOnly(False)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.gridLayout.addWidget(self.lineEdit_name, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(combine_func_detatil_dialog)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(combine_func_detatil_dialog)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(combine_func_detatil_dialog)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.plainTextEdit_introduction = QtWidgets.QPlainTextEdit(combine_func_detatil_dialog)
        self.plainTextEdit_introduction.setReadOnly(False)
        self.plainTextEdit_introduction.setObjectName("plainTextEdit_introduction")
        self.gridLayout.addWidget(self.plainTextEdit_introduction, 2, 1, 1, 2)
        self.treeWidget_variable = QtWidgets.QTreeWidget(combine_func_detatil_dialog)
        self.treeWidget_variable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.treeWidget_variable.setObjectName("treeWidget_variable")
        self.treeWidget_variable.header().setDefaultSectionSize(100)
        self.gridLayout.addWidget(self.treeWidget_variable, 1, 1, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_combine = QtWidgets.QPushButton(combine_func_detatil_dialog)
        self.button_combine.setObjectName("button_combine")
        self.horizontalLayout.addWidget(self.button_combine)
        self.button_test = QtWidgets.QPushButton(combine_func_detatil_dialog)
        self.button_test.setObjectName("button_test")
        self.horizontalLayout.addWidget(self.button_test)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(combine_func_detatil_dialog)
        QtCore.QMetaObject.connectSlotsByName(combine_func_detatil_dialog)

    def retranslateUi(self, combine_func_detatil_dialog):
        _translate = QtCore.QCoreApplication.translate
        combine_func_detatil_dialog.setWindowTitle(_translate("combine_func_detatil_dialog", "功能详情"))
        self.label_3.setText(_translate("combine_func_detatil_dialog", "输入参数"))
        self.label_2.setText(_translate("combine_func_detatil_dialog", "功能介绍"))
        self.label.setText(_translate("combine_func_detatil_dialog", "功能名称"))
        self.treeWidget_variable.setSortingEnabled(True)
        self.treeWidget_variable.headerItem().setText(0, _translate("combine_func_detatil_dialog", "部件号"))
        self.treeWidget_variable.headerItem().setText(1, _translate("combine_func_detatil_dialog", "控件名称"))
        self.treeWidget_variable.headerItem().setText(2, _translate("combine_func_detatil_dialog", "变量名"))
        self.treeWidget_variable.headerItem().setText(3, _translate("combine_func_detatil_dialog", "值"))
        self.button_combine.setText(_translate("combine_func_detatil_dialog", "合成"))
        self.button_test.setText(_translate("combine_func_detatil_dialog", "任务测试"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    combine_func_detatil_dialog = QtWidgets.QDialog()
    ui = Ui_combine_func_detatil_dialog()
    ui.setupUi(combine_func_detatil_dialog)
    combine_func_detatil_dialog.show()
    sys.exit(app.exec_())
