# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tools_tunnel_edit_script_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tools_tunnel_edit_script_dialog(object):
    def setupUi(self, tools_tunnel_edit_script_dialog):
        tools_tunnel_edit_script_dialog.setObjectName("tools_tunnel_edit_script_dialog")
        tools_tunnel_edit_script_dialog.resize(534, 493)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(tools_tunnel_edit_script_dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(tools_tunnel_edit_script_dialog)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_position = QtWidgets.QLineEdit(tools_tunnel_edit_script_dialog)
        self.lineEdit_position.setFrame(False)
        self.lineEdit_position.setReadOnly(True)
        self.lineEdit_position.setObjectName("lineEdit_position")
        self.gridLayout.addWidget(self.lineEdit_position, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(tools_tunnel_edit_script_dialog)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_package = QtWidgets.QLineEdit(tools_tunnel_edit_script_dialog)
        self.lineEdit_package.setFrame(False)
        self.lineEdit_package.setReadOnly(True)
        self.lineEdit_package.setObjectName("lineEdit_package")
        self.gridLayout.addWidget(self.lineEdit_package, 1, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.button_edit = QtWidgets.QToolButton(tools_tunnel_edit_script_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_edit.sizePolicy().hasHeightForWidth())
        self.button_edit.setSizePolicy(sizePolicy)
        self.button_edit.setObjectName("button_edit")
        self.horizontalLayout.addWidget(self.button_edit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plainTextEdit_head = QtWidgets.QPlainTextEdit(tools_tunnel_edit_script_dialog)
        self.plainTextEdit_head.setMaximumSize(QtCore.QSize(16777215, 65))
        self.plainTextEdit_head.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.plainTextEdit_head.setFrameShadow(QtWidgets.QFrame.Plain)
        self.plainTextEdit_head.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.plainTextEdit_head.setReadOnly(True)
        self.plainTextEdit_head.setPlainText("")
        self.plainTextEdit_head.setObjectName("plainTextEdit_head")
        self.verticalLayout.addWidget(self.plainTextEdit_head)
        self.plainTextEdit_body = QtWidgets.QPlainTextEdit(tools_tunnel_edit_script_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_body.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_body.setSizePolicy(sizePolicy)
        self.plainTextEdit_body.setReadOnly(True)
        self.plainTextEdit_body.setTabStopWidth(24)
        self.plainTextEdit_body.setObjectName("plainTextEdit_body")
        self.verticalLayout.addWidget(self.plainTextEdit_body)
        self.plainTextEdit_tail = QtWidgets.QPlainTextEdit(tools_tunnel_edit_script_dialog)
        self.plainTextEdit_tail.setMaximumSize(QtCore.QSize(16777215, 25))
        self.plainTextEdit_tail.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.plainTextEdit_tail.setFrameShadow(QtWidgets.QFrame.Plain)
        self.plainTextEdit_tail.setReadOnly(True)
        self.plainTextEdit_tail.setPlainText("")
        self.plainTextEdit_tail.setObjectName("plainTextEdit_tail")
        self.verticalLayout.addWidget(self.plainTextEdit_tail)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(tools_tunnel_edit_script_dialog)
        QtCore.QMetaObject.connectSlotsByName(tools_tunnel_edit_script_dialog)

    def retranslateUi(self, tools_tunnel_edit_script_dialog):
        _translate = QtCore.QCoreApplication.translate
        tools_tunnel_edit_script_dialog.setWindowTitle(_translate("tools_tunnel_edit_script_dialog", "修改内置脚本"))
        self.label.setText(_translate("tools_tunnel_edit_script_dialog", " 脚本"))
        self.label_2.setText(_translate("tools_tunnel_edit_script_dialog", " 导入的包"))
        self.button_edit.setText(_translate("tools_tunnel_edit_script_dialog", "编辑\n"
"脚本"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tools_tunnel_edit_script_dialog = QtWidgets.QDialog()
    ui = Ui_tools_tunnel_edit_script_dialog()
    ui.setupUi(tools_tunnel_edit_script_dialog)
    tools_tunnel_edit_script_dialog.show()
    sys.exit(app.exec_())
