# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tools_tunnel_edit_customscript_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tools_tunnel_edit_customscript_dialog(object):
    def setupUi(self, tools_tunnel_edit_customscript_dialog):
        tools_tunnel_edit_customscript_dialog.setObjectName("tools_tunnel_edit_customscript_dialog")
        tools_tunnel_edit_customscript_dialog.resize(532, 495)
        self.verticalLayout = QtWidgets.QVBoxLayout(tools_tunnel_edit_customscript_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(tools_tunnel_edit_customscript_dialog)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_position = QtWidgets.QLineEdit(tools_tunnel_edit_customscript_dialog)
        self.lineEdit_position.setFrame(False)
        self.lineEdit_position.setReadOnly(True)
        self.lineEdit_position.setObjectName("lineEdit_position")
        self.gridLayout.addWidget(self.lineEdit_position, 0, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.button_edit = QtWidgets.QToolButton(tools_tunnel_edit_customscript_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_edit.sizePolicy().hasHeightForWidth())
        self.button_edit.setSizePolicy(sizePolicy)
        self.button_edit.setObjectName("button_edit")
        self.horizontalLayout.addWidget(self.button_edit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.plainTextEdit_body = QtWidgets.QPlainTextEdit(tools_tunnel_edit_customscript_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_body.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_body.setSizePolicy(sizePolicy)
        self.plainTextEdit_body.setReadOnly(True)
        self.plainTextEdit_body.setTabStopWidth(24)
        self.plainTextEdit_body.setObjectName("plainTextEdit_body")
        self.verticalLayout.addWidget(self.plainTextEdit_body)
        self.notice = QtWidgets.QTextEdit(tools_tunnel_edit_customscript_dialog)
        self.notice.setMaximumSize(QtCore.QSize(16777215, 55))
        self.notice.setReadOnly(True)
        self.notice.setObjectName("notice")
        self.verticalLayout.addWidget(self.notice)

        self.retranslateUi(tools_tunnel_edit_customscript_dialog)
        QtCore.QMetaObject.connectSlotsByName(tools_tunnel_edit_customscript_dialog)

    def retranslateUi(self, tools_tunnel_edit_customscript_dialog):
        _translate = QtCore.QCoreApplication.translate
        tools_tunnel_edit_customscript_dialog.setWindowTitle(_translate("tools_tunnel_edit_customscript_dialog", "修改自定义脚本"))
        self.label.setText(_translate("tools_tunnel_edit_customscript_dialog", " 脚本"))
        self.button_edit.setText(_translate("tools_tunnel_edit_customscript_dialog", "编辑\n"
"脚本"))
        self.notice.setHtml(_translate("tools_tunnel_edit_customscript_dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">注意：</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">数据处理函数命名示例：    deal_data(input_1, input_2)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">返回值示例：        return output_1, output_2</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tools_tunnel_edit_customscript_dialog = QtWidgets.QDialog()
    ui = Ui_tools_tunnel_edit_customscript_dialog()
    ui.setupUi(tools_tunnel_edit_customscript_dialog)
    tools_tunnel_edit_customscript_dialog.show()
    sys.exit(app.exec_())
