# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'works_task_result_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_works_tasks_dialog(object):
    def setupUi(self, works_tasks_dialog):
        works_tasks_dialog.setObjectName("works_tasks_dialog")
        works_tasks_dialog.resize(591, 523)
        self.gridLayout = QtWidgets.QGridLayout(works_tasks_dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(works_tasks_dialog)
        self.widget.setObjectName("widget")
        self.tabWidget = QtWidgets.QTabWidget(self.widget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 30, 561, 471))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.textEdit = QtWidgets.QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 561, 451))
        self.textEdit.setObjectName("textEdit")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(10, 10, 54, 12))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(310, 10, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(420, 10, 101, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(154, 10, 121, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(works_tasks_dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(works_tasks_dialog)

    def retranslateUi(self, works_tasks_dialog):
        _translate = QtCore.QCoreApplication.translate
        works_tasks_dialog.setWindowTitle(_translate("works_tasks_dialog", "查看任务执行结果"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("works_tasks_dialog", "阶段一"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("works_tasks_dialog", "阶段二"))
        self.label.setText(_translate("works_tasks_dialog", "任务一"))
        self.pushButton.setText(_translate("works_tasks_dialog", "导出为文件"))
        self.pushButton_2.setText(_translate("works_tasks_dialog", "放到我的结果集"))
        self.pushButton_3.setText(_translate("works_tasks_dialog", "发送到手动处理窗口"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    works_tasks_dialog = QtWidgets.QDialog()
    ui = Ui_works_tasks_dialog()
    ui.setupUi(works_tasks_dialog)
    works_tasks_dialog.show()
    sys.exit(app.exec_())
