# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'works_task_set_timer_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_works_task_set_timer_dialog(object):
    def setupUi(self, works_task_set_timer_dialog):
        works_task_set_timer_dialog.setObjectName("works_task_set_timer_dialog")
        works_task_set_timer_dialog.resize(373, 137)
        self.verticalLayout = QtWidgets.QVBoxLayout(works_task_set_timer_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.spinBox_hour = QtWidgets.QSpinBox(works_task_set_timer_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_hour.sizePolicy().hasHeightForWidth())
        self.spinBox_hour.setSizePolicy(sizePolicy)
        self.spinBox_hour.setFrame(False)
        self.spinBox_hour.setObjectName("spinBox_hour")
        self.horizontalLayout_2.addWidget(self.spinBox_hour)
        self.label = QtWidgets.QLabel(works_task_set_timer_dialog)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.spinBox_minute = QtWidgets.QSpinBox(works_task_set_timer_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_minute.sizePolicy().hasHeightForWidth())
        self.spinBox_minute.setSizePolicy(sizePolicy)
        self.spinBox_minute.setFrame(False)
        self.spinBox_minute.setMaximum(59)
        self.spinBox_minute.setObjectName("spinBox_minute")
        self.horizontalLayout_2.addWidget(self.spinBox_minute)
        self.label_2 = QtWidgets.QLabel(works_task_set_timer_dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinBox_second = QtWidgets.QSpinBox(works_task_set_timer_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_second.sizePolicy().hasHeightForWidth())
        self.spinBox_second.setSizePolicy(sizePolicy)
        self.spinBox_second.setFrame(False)
        self.spinBox_second.setMaximum(59)
        self.spinBox_second.setObjectName("spinBox_second")
        self.horizontalLayout_2.addWidget(self.spinBox_second)
        self.label_3 = QtWidgets.QLabel(works_task_set_timer_dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.widget = QtWidgets.QWidget(works_task_set_timer_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(58, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.button_yes = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_yes.sizePolicy().hasHeightForWidth())
        self.button_yes.setSizePolicy(sizePolicy)
        self.button_yes.setObjectName("button_yes")
        self.horizontalLayout.addWidget(self.button_yes)
        spacerItem1 = QtWidgets.QSpacerItem(58, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.button_no = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_no.sizePolicy().hasHeightForWidth())
        self.button_no.setSizePolicy(sizePolicy)
        self.button_no.setObjectName("button_no")
        self.horizontalLayout.addWidget(self.button_no)
        spacerItem2 = QtWidgets.QSpacerItem(58, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(works_task_set_timer_dialog)
        QtCore.QMetaObject.connectSlotsByName(works_task_set_timer_dialog)

    def retranslateUi(self, works_task_set_timer_dialog):
        _translate = QtCore.QCoreApplication.translate
        works_task_set_timer_dialog.setWindowTitle(_translate("works_task_set_timer_dialog", "设置定时"))
        self.label.setText(_translate("works_task_set_timer_dialog", "小时"))
        self.label_2.setText(_translate("works_task_set_timer_dialog", "分钟"))
        self.label_3.setText(_translate("works_task_set_timer_dialog", "秒"))
        self.button_yes.setText(_translate("works_task_set_timer_dialog", "确定"))
        self.button_no.setText(_translate("works_task_set_timer_dialog", "取消"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    works_task_set_timer_dialog = QtWidgets.QDialog()
    ui = Ui_works_task_set_timer_dialog()
    ui.setupUi(works_task_set_timer_dialog)
    works_task_set_timer_dialog.show()
    sys.exit(app.exec_())
