# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'works_task_input_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_works_task_input_dialog(object):
    def setupUi(self, works_task_input_dialog):
        works_task_input_dialog.setObjectName("works_task_input_dialog")
        works_task_input_dialog.resize(444, 385)
        self.gridLayout = QtWidgets.QGridLayout(works_task_input_dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.button_yes = QtWidgets.QPushButton(works_task_input_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_yes.sizePolicy().hasHeightForWidth())
        self.button_yes.setSizePolicy(sizePolicy)
        self.button_yes.setObjectName("button_yes")
        self.gridLayout.addWidget(self.button_yes, 2, 1, 1, 1)
        self.button_no = QtWidgets.QPushButton(works_task_input_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_no.sizePolicy().hasHeightForWidth())
        self.button_no.setSizePolicy(sizePolicy)
        self.button_no.setObjectName("button_no")
        self.gridLayout.addWidget(self.button_no, 2, 3, 1, 1)
        self.task_name = QtWidgets.QLineEdit(works_task_input_dialog)
        self.task_name.setObjectName("task_name")
        self.gridLayout.addWidget(self.task_name, 0, 1, 1, 4)
        self.button_set_timer = QtWidgets.QPushButton(works_task_input_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_set_timer.sizePolicy().hasHeightForWidth())
        self.button_set_timer.setSizePolicy(sizePolicy)
        self.button_set_timer.setObjectName("button_set_timer")
        self.gridLayout.addWidget(self.button_set_timer, 0, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(works_task_input_dialog)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.treeWidget = QtWidgets.QTreeWidget(works_task_input_dialog)
        self.treeWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.header().setDefaultSectionSize(110)
        self.gridLayout.addWidget(self.treeWidget, 1, 0, 1, 6)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 5, 1, 1)

        self.retranslateUi(works_task_input_dialog)
        QtCore.QMetaObject.connectSlotsByName(works_task_input_dialog)

    def retranslateUi(self, works_task_input_dialog):
        _translate = QtCore.QCoreApplication.translate
        works_task_input_dialog.setWindowTitle(_translate("works_task_input_dialog", "设置任务参数"))
        self.button_yes.setText(_translate("works_task_input_dialog", "执行"))
        self.button_no.setText(_translate("works_task_input_dialog", "取消"))
        self.button_set_timer.setText(_translate("works_task_input_dialog", "设置定时"))
        self.label_2.setText(_translate("works_task_input_dialog", "任务名称"))
        self.treeWidget.headerItem().setText(0, _translate("works_task_input_dialog", "变量名"))
        self.treeWidget.headerItem().setText(1, _translate("works_task_input_dialog", "位置"))
        self.treeWidget.headerItem().setText(2, _translate("works_task_input_dialog", "控件名"))
        self.treeWidget.headerItem().setText(3, _translate("works_task_input_dialog", "值"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    works_task_input_dialog = QtWidgets.QDialog()
    ui = Ui_works_task_input_dialog()
    ui.setupUi(works_task_input_dialog)
    works_task_input_dialog.show()
    sys.exit(app.exec_())
